<a href="https://colab.research.google.com/github/lucasalechilet/Curso_FCD/blob/main/preprocesamiento_y_escalamiento_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análisis de Caso: Preprocesamiento y Escalamiento de Datos


---

## 1. Creación del Dataset

In [1]:
#link a github https://github.com/lucasalechilet/Curso_FCD/blob/main/preprocesamiento_y_escalamiento_de_datos.ipynb

import pandas as pd
import numpy as np

data = {
    'ID': [1, 2, 3, 4],
    'Edad': [25, 45, 30, 40],
    'Ciudad': ['Madrid', 'Sevilla', 'Madrid', 'Barcelona'],
    'Ingresos': [30000, 50000, np.nan, 40000]
}

df = pd.DataFrame(data)  #se genera el dataframe con los datos iniciales
df

   ID  Edad     Ciudad  Ingresos
0   1    25     Madrid   30000.0
1   2    45    Sevilla   50000.0
2   3    30     Madrid       NaN
3   4    40  Barcelona   40000.0

## 2. Imputación de valores faltantes

In [2]:
mean_ingresos = df['Ingresos'].mean()
df['Ingresos'] = df['Ingresos'].fillna(mean_ingresos) #usamos fillna para llenar con la media de ingresos calculada

print("media usada para imputación:", mean_ingresos)
df

Media usada para imputación: 40000.0

   ID  Edad     Ciudad  Ingresos
0   1    25     Madrid   30000.0
1   2    45    Sevilla   50000.0
2   3    30     Madrid   40000.0
3   4    40  Barcelona   40000.0

## 3. Codificación de variables categóricas

### Label Encoding

In [3]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Ciudad_Label'] = le.fit_transform(df['Ciudad']) #aplicamos labelencoder, lo que permitirá codificar cada ciudad como número entero >=0

df

   ID  Edad     Ciudad  Ingresos  Ciudad_Label
0   1    25     Madrid   30000.0             1
1   2    45    Sevilla   50000.0             2
2   3    30     Madrid   40000.0             1
3   4    40  Barcelona   40000.0             0

### One-Hot Encoding

In [4]:
df_onehot = pd.get_dummies(df, columns=['Ciudad']) #aplicamos onehotencoder a ciudad, lo que permitirá tener un label booleano para cada ciudad, en lugar de 1 sóla columna con string
df_onehot

,ID,Edad,Ingresos,Ciudad_Label,Ciudad_Barcelona,Ciudad_Madrid,Ciudad_Sevilla
0,1,25,30000.0,1,False,True,False
1,2,45,50000.0,2,False,False,True
2,3,30,40000.0,1,False,True,False
3,4,40,40000.0,0,True,False,False

### Variables Dummy (drop_first=True)

In [6]:
df_dummy = pd.get_dummies(df, columns=['Ciudad'], drop_first=True) #aplicamos get_dummies con drop_first=True, lo que eliminará
df_dummy                                                            #una de las columnas implícitas de ciudad. esto se hace para evitar colinealidad,
                                                                    # pues Ciudad_Barcelona queda implícita cuando las otras son False

   ID  Edad  Ingresos  Ciudad_Label  Ciudad_Madrid  Ciudad_Sevilla
0   1    25   30000.0             1           True           False
1   2    45   50000.0             2          False            True
2   3    30   40000.0             1           True           False
3   4    40   40000.0             0          False           False

## 4. Escalamiento de variables numéricas

### Normalización Min-Max

In [8]:
from sklearn.preprocessing import MinMaxScaler

scaler_minmax = MinMaxScaler()
df[['Edad_MinMax', 'Ingresos_MinMax']] = scaler_minmax.fit_transform(df[['Edad', 'Ingresos']]) #normalizamos edad e ingresos con min-max

df

   ID  Edad     Ciudad  Ingresos  Ciudad_Label  Edad_MinMax  Ingresos_MinMax
0   1    25     Madrid   30000.0             1         0.00              0.0
1   2    45    Sevilla   50000.0             2         1.00              1.0
2   3    30     Madrid   40000.0             1         0.25              0.5
3   4    40  Barcelona   40000.0             0         0.75              0.5

### Estandarización Z-Score

In [10]:
from sklearn.preprocessing import StandardScaler

scaler_std = StandardScaler()
df[['Edad_Z', 'Ingresos_Z']] = scaler_std.fit_transform(df[['Edad', 'Ingresos']]) #estandarizamos edad e ingresos con método z-score

df

,ID,Edad,Ciudad,Ingresos,Ciudad_Label,Edad_MinMax,Ingresos_MinMax,Edad_Z,Ingresos_Z
0,1,25,Madrid,30000.0,1,0.00,0.0,-1.264911,-1.414214
1,2,45,Sevilla,50000.0,2,1.00,1.0,1.264911,1.414214
2,3,30,Madrid,40000.0,1,0.25,0.5,-0.632456,0.000000
3,4,40,Barcelona,40000.0,0,0.75,0.5,0.632456,0.000000

## 5. Exportación del dataset preprocesado

In [11]:
df.to_csv('dataset_preprocesado.csv', index=False)
print("Archivo guardado como dataset_preprocesado.csv")

Archivo guardado como dataset_preprocesado.csv

## 6. Conclusiones
Realizar estas tareas es fundamental porque la calidad de los datos impacta directamente en el desempeño del modelo de Machine Learning. El preprocesamiento permite que los algoritmos procesen variables categóricas al convertirlas a un formato numérico y evita que valores nulos o escalas muy distintas entre variables generen sesgos o errores en el aprendizaje.

En cuanto a las técnicas de escalamiento, la principal diferencia es que la normalización Min-Max transforma los datos a un rango específico, lo cual es muy útil cuando los datos no siguen una distribución normal. Por otro lado, la estandarización Z-Score reescala los datos para que tengan una media de cero y una desviación estándar de uno, siendo más robusta ante la presencia de valores atípicos y preferible para algoritmos que asumen distribuciones gaussianas.